# DigitalOcean App Platform Configuration
# This file defines the deployment for both backend and frontend

name: ghl-onboarding
region: nyc

# Backend Service (FastAPI)
services:
  - name: backend
    github:
      repo: 1di210299/ghl-onboarding
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    
    http_port: 8000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    routes:
      - path: /api
    
    envs:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        scope: RUN_TIME
        type: SECRET
      
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
        scope: RUN_TIME
        type: SECRET
      
      - key: SUPABASE_ANON_KEY
        value: ${SUPABASE_ANON_KEY}
        scope: RUN_TIME
        type: SECRET
      
      - key: SUPABASE_SERVICE_KEY
        value: ${SUPABASE_SERVICE_KEY}
        scope: RUN_TIME
        type: SECRET
      
      - key: GHL_API_KEY
        value: ${GHL_API_KEY}
        scope: RUN_TIME
        type: SECRET
      
      - key: GHL_LOCATION_ID
        value: ${GHL_LOCATION_ID}
        scope: RUN_TIME
      
      - key: GHL_API_URL
        value: https://rest.gohighlevel.com/v1
        scope: RUN_TIME
      
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        scope: RUN_TIME
        type: SECRET
      
      - key: ENVIRONMENT
        value: production
        scope: RUN_TIME
      
      - key: LOG_LEVEL
        value: INFO
        scope: RUN_TIME
      
      - key: BACKEND_HOST
        value: 0.0.0.0
        scope: RUN_TIME
      
      - key: PORT
        value: "8000"
        scope: RUN_TIME

# Frontend Service (Next.js)
  - name: frontend
    github:
      repo: 1di210299/ghl-onboarding
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    dockerfile_path: frontend/Dockerfile
    
    http_port: 3000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}
        scope: RUN_AND_BUILD_TIME
      
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: ${SUPABASE_URL}
        scope: RUN_AND_BUILD_TIME
      
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: ${SUPABASE_ANON_KEY}
        scope: RUN_AND_BUILD_TIME
